version: '3.8'

services:
  database:
    image : mongo
    container_name: mongo
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - ./seed_mongo.js:/docker-entrypoint-initdb.d/seed_mongo.js
